# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/mainScreen.ui'
#
# Created: Wed Jan  1 16:59:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainScreen(object):
    def setupUi(self, mainScreen):
        mainScreen.setObjectName("mainScreen")
        mainScreen.setWindowModality(QtCore.Qt.NonModal)
        mainScreen.setEnabled(True)
        mainScreen.resize(410, 300)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainScreen.sizePolicy().hasHeightForWidth())
        mainScreen.setSizePolicy(sizePolicy)
        mainScreen.setMinimumSize(QtCore.QSize(410, 300))
        mainScreen.setMaximumSize(QtCore.QSize(410, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/swords.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainScreen.setWindowIcon(icon)
        mainScreen.setTabPosition(QtGui.QTabWidget.North)
        mainScreen.setTabShape(QtGui.QTabWidget.Rounded)
        mainScreen.setIconSize(QtCore.QSize(48, 48))
        mainScreen.setElideMode(QtCore.Qt.ElideNone)
        self.raidTab = QtGui.QWidget()
        self.raidTab.setObjectName("raidTab")
        self.raidTable = QtGui.QTableWidget(self.raidTab)
        self.raidTable.setGeometry(QtCore.QRect(0, 0, 406, 230))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raidTable.sizePolicy().hasHeightForWidth())
        self.raidTable.setSizePolicy(sizePolicy)
        self.raidTable.setMinimumSize(QtCore.QSize(404, 230))
        self.raidTable.setMaximumSize(QtCore.QSize(406, 267))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.raidTable.setFont(font)
        self.raidTable.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.raidTable.setFrameShadow(QtGui.QFrame.Sunken)
        self.raidTable.setLineWidth(0)
        self.raidTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.raidTable.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.raidTable.setDragDropOverwriteMode(False)
        self.raidTable.setAlternatingRowColors(True)
        self.raidTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.raidTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.raidTable.setTextElideMode(QtCore.Qt.ElideLeft)
        self.raidTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.raidTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.raidTable.setShowGrid(True)
        self.raidTable.setGridStyle(QtCore.Qt.DotLine)
        self.raidTable.setWordWrap(False)
        self.raidTable.setCornerButtonEnabled(False)
        self.raidTable.setColumnCount(13)
        self.raidTable.setObjectName("raidTable")
        self.raidTable.setColumnCount(13)
        self.raidTable.setRowCount(0)
        self.raidTable.horizontalHeader().setCascadingSectionResizes(False)
        self.raidTable.horizontalHeader().setDefaultSectionSize(30)
        self.raidTable.horizontalHeader().setHighlightSections(False)
        self.raidTable.horizontalHeader().setMinimumSectionSize(30)
        self.raidTable.horizontalHeader().setStretchLastSection(True)
        self.raidTable.verticalHeader().setVisible(False)
        self.raidTable.verticalHeader().setDefaultSectionSize(25)
        self.raidTable.verticalHeader().setMinimumSectionSize(25)
        self.buttonRaid = QtGui.QPushButton(self.raidTab)
        self.buttonRaid.setGeometry(QtCore.QRect(0, 230, 50, 38))
        self.buttonRaid.setIconSize(QtCore.QSize(32, 32))
        self.buttonRaid.setObjectName("buttonRaid")
        self.buttonAdd = QtGui.QPushButton(self.raidTab)
        self.buttonAdd.setGeometry(QtCore.QRect(210, 230, 50, 38))
        self.buttonAdd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonAdd.setObjectName("buttonAdd")
        self.buttonDelete = QtGui.QPushButton(self.raidTab)
        self.buttonDelete.setGeometry(QtCore.QRect(260, 230, 60, 38))
        self.buttonDelete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonDelete.setObjectName("buttonDelete")
        self.raidProgress = QtGui.QProgressBar(self.raidTab)
        self.raidProgress.setGeometry(QtCore.QRect(50, 231, 159, 36))
        self.raidProgress.setProperty("value", 24)
        self.raidProgress.setObjectName("raidProgress")
        self.buttonDeleteAll = QtGui.QPushButton(self.raidTab)
        self.buttonDeleteAll.setGeometry(QtCore.QRect(320, 230, 86, 38))
        self.buttonDeleteAll.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonDeleteAll.setObjectName("buttonDeleteAll")
        mainScreen.addTab(self.raidTab, "")
        self.cropperTab = QtGui.QWidget()
        self.cropperTab.setObjectName("cropperTab")
        self.searchButton = QtGui.QPushButton(self.cropperTab)
        self.searchButton.setGeometry(QtCore.QRect(0, 230, 71, 38))
        self.searchButton.setObjectName("searchButton")
        self.find9Ccheck = QtGui.QCheckBox(self.cropperTab)
        self.find9Ccheck.setGeometry(QtCore.QRect(186, 238, 97, 22))
        self.find9Ccheck.setObjectName("find9Ccheck")
        self.maxDist = QtGui.QLineEdit(self.cropperTab)
        self.maxDist.setGeometry(QtCore.QRect(285, 235, 113, 27))
        self.maxDist.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.maxDist.setObjectName("maxDist")
        self.cFindTable = QtGui.QTableWidget(self.cropperTab)
        self.cFindTable.setGeometry(QtCore.QRect(0, 0, 406, 230))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cFindTable.sizePolicy().hasHeightForWidth())
        self.cFindTable.setSizePolicy(sizePolicy)
        self.cFindTable.setMinimumSize(QtCore.QSize(404, 230))
        self.cFindTable.setMaximumSize(QtCore.QSize(406, 267))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cFindTable.setFont(font)
        self.cFindTable.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.cFindTable.setFrameShadow(QtGui.QFrame.Sunken)
        self.cFindTable.setLineWidth(0)
        self.cFindTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cFindTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.cFindTable.setDragDropOverwriteMode(False)
        self.cFindTable.setAlternatingRowColors(True)
        self.cFindTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.cFindTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.cFindTable.setTextElideMode(QtCore.Qt.ElideLeft)
        self.cFindTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.cFindTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.cFindTable.setShowGrid(True)
        self.cFindTable.setGridStyle(QtCore.Qt.DotLine)
        self.cFindTable.setWordWrap(False)
        self.cFindTable.setCornerButtonEnabled(False)
        self.cFindTable.setColumnCount(5)
        self.cFindTable.setObjectName("cFindTable")
        self.cFindTable.setColumnCount(5)
        self.cFindTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cFindTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cFindTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cFindTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.cFindTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.cFindTable.setHorizontalHeaderItem(4, item)
        self.cFindTable.horizontalHeader().setCascadingSectionResizes(False)
        self.cFindTable.horizontalHeader().setDefaultSectionSize(70)
        self.cFindTable.horizontalHeader().setHighlightSections(False)
        self.cFindTable.horizontalHeader().setMinimumSectionSize(20)
        self.cFindTable.horizontalHeader().setStretchLastSection(True)
        self.cFindTable.verticalHeader().setVisible(False)
        self.cFindTable.verticalHeader().setDefaultSectionSize(25)
        self.cFindTable.verticalHeader().setMinimumSectionSize(25)
        self.fieldX = QtGui.QLineEdit(self.cropperTab)
        self.fieldX.setGeometry(QtCore.QRect(85, 236, 40, 27))
        self.fieldX.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.fieldX.setObjectName("fieldX")
        self.fieldY = QtGui.QLineEdit(self.cropperTab)
        self.fieldY.setGeometry(QtCore.QRect(140, 236, 40, 27))
        self.fieldY.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.fieldY.setObjectName("fieldY")
        mainScreen.addTab(self.cropperTab, "")
        self.troopTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.troopTab.sizePolicy().hasHeightForWidth())
        self.troopTab.setSizePolicy(sizePolicy)
        self.troopTab.setObjectName("troopTab")
        mainScreen.addTab(self.troopTab, "")

        self.retranslateUi(mainScreen)
        mainScreen.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainScreen)

    def retranslateUi(self, mainScreen):
        mainScreen.setWindowTitle(QtGui.QApplication.translate("mainScreen", "Travian Raider 2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRaid.setText(QtGui.QApplication.translate("mainScreen", "Raid", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd.setText(QtGui.QApplication.translate("mainScreen", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDelete.setText(QtGui.QApplication.translate("mainScreen", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeleteAll.setText(QtGui.QApplication.translate("mainScreen", "Delete All", None, QtGui.QApplication.UnicodeUTF8))
        mainScreen.setTabText(mainScreen.indexOf(self.raidTab), QtGui.QApplication.translate("mainScreen", "Raids", None, QtGui.QApplication.UnicodeUTF8))
        mainScreen.setTabToolTip(mainScreen.indexOf(self.raidTab), QtGui.QApplication.translate("mainScreen", "Manage Raids", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("mainScreen", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.find9Ccheck.setText(QtGui.QApplication.translate("mainScreen", "Find 9C", None, QtGui.QApplication.UnicodeUTF8))
        self.maxDist.setPlaceholderText(QtGui.QApplication.translate("mainScreen", "Max Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.cFindTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("mainScreen", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.cFindTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("mainScreen", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.cFindTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("mainScreen", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.cFindTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("mainScreen", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cFindTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("mainScreen", "Oases", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldX.setPlaceholderText(QtGui.QApplication.translate("mainScreen", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldY.setPlaceholderText(QtGui.QApplication.translate("mainScreen", "Y", None, QtGui.QApplication.UnicodeUTF8))
        mainScreen.setTabText(mainScreen.indexOf(self.cropperTab), QtGui.QApplication.translate("mainScreen", "cFind", None, QtGui.QApplication.UnicodeUTF8))
        mainScreen.setTabText(mainScreen.indexOf(self.troopTab), QtGui.QApplication.translate("mainScreen", "Troops", None, QtGui.QApplication.UnicodeUTF8))
        mainScreen.setTabToolTip(mainScreen.indexOf(self.troopTab), QtGui.QApplication.translate("mainScreen", "Manage Troops", None, QtGui.QApplication.UnicodeUTF8))

import imgs_rc
